import org.objectweb.asm.*;

public class ASMDemo {
    /*
    * A demo generated by ChatGPT to show how to use ASM
    * */
    public static void main(String[] args) throws Exception {
        ClassReader cr = new ClassReader("java.lang.String");

        ClassVisitor cv = new ClassVisitor(Opcodes.ASM9) {

            @Override
            public MethodVisitor visitMethod(int access, String name, String desc, String signature, String[] exceptions) {
                System.out.println("方法: " + name + "   描述符: " + desc);
                return super.visitMethod(access, name, desc, signature, exceptions);
            }
        };
        cr.accept(cv, 0);
    }
}